2021-04-25 13:15:33,011 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:43]
2021-04-25 13:15:35,400 ERROR: Exception on /article [POST] [in /home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ilya-debian/PyBlog/app/routes.py", line 151, in article
    return render_template("article.html", title='Create article',form=form, posts=posts)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ilya-debian/PyBlog/app/templates/article.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ilya-debian/PyBlog/app/templates/base.html", line 39, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ilya-debian/PyBlog/app/templates/article.html", line 10, in block "content"
    <br>{% for error in form.header.errors %}
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ArticleForm object' has no attribute 'header'
2021-04-25 13:16:56,051 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:43]
2021-04-25 13:16:58,817 ERROR: Exception on /article [POST] [in /home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ilya-debian/PyBlog/app/routes.py", line 151, in article
    return render_template("article.html", title='Create article',form=form, posts=posts)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ilya-debian/PyBlog/app/templates/article.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ilya-debian/PyBlog/app/templates/base.html", line 39, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ilya-debian/PyBlog/app/templates/article.html", line 10, in block "content"
    <br>{% for error in form.header.errors %}
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ArticleForm object' has no attribute 'header'
2021-04-25 13:17:11,985 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:43]
2021-04-25 13:19:06,301 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:43]
2021-04-25 13:19:16,318 ERROR: Exception on /article [POST] [in /home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ilya-debian/PyBlog/app/routes.py", line 129, in article
    post = Post(body = form.post.data, title=form.header.data, author=current_user)
AttributeError: 'ArticleForm' object has no attribute 'header'
2021-04-25 13:19:57,160 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:43]
2021-04-25 13:21:13,115 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:43]
2021-04-25 13:25:37,506 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:43]
2021-04-25 13:28:53,394 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:43]
2021-04-25 13:31:24,166 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:43]
2021-04-25 13:36:54,641 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:43]
2021-04-25 13:37:09,852 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:43]
2021-04-25 13:37:19,473 ERROR: Exception on /index [GET] [in /home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ilya-debian/PyBlog/app/routes.py", line 23, in index
    if posts.has_next else None
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'explore' with values ['page']. Did you mean 'edit_profile' instead?
